drop table if exists drone_medication_list;
drop table drone if exists;
drop table medication if exists;
create table drone (
       id bigint generated by default as identity,
       battery_capacity numeric(38,2),
       model smallint,
       serial_number varchar(255),
       state smallint,
       weight_limit integer,
       primary key (id)
);
create table medication (
        id bigint generated by default as identity,
        code varchar(255),
        image varchar(255),
        name varchar(255),
        weight integer,
        primary key (id)
);
create table drone_medication_list (
    drone_id bigint not null,
    medication_list_id bigint not null
)