drop table drone if exists;
create table drone (
       id bigint generated by default as identity,
       battery_capacity numeric(38,2),
       model smallint,
       serial_number varchar(255),
       state smallint,
       weight_limit integer,
       primary key (id)
);
drop table medication if exists;
create table medication (
        id bigint generated by default as identity,
        code varchar(255),
        image varchar(255),
        name varchar(255),
        weight integer,
        primary key (id)
);